\documentclass{article}
  \usepackage{amsmath,color,hyperref}
  \usepackage[round]{natbib}
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage[english]{babel}
  \usepackage{lucidabr}
  \usepackage[noae]{Sweave}

  %\VignetteIndexEntry{Introduction to actuar}
  %\VignettePackage{actuar}

  \title{Introduction to \pkg{actuar}}
  \author{Christophe Dutang \\ ISFA, Université Claude Bernard Lyon 1 \\[3ex]
    Vincent Goulet \\ École d'actuariat, Université Laval \\[3ex]
    Mathieu Pigeon \\ École d'actuariat, Université Laval}
  \date{}

  \newcommand{\proglang}[1]{\textsf{#1}}
  \newcommand{\pkg}[1]{\textbf{#1}}

  \bibliographystyle{plainnat}

  \definecolor{Red}{rgb}{0.7,0,0}
  \definecolor{Blue}{rgb}{0,0,0.8}
  \hypersetup{%
    hyperindex = {true},
    colorlinks = {true},
    linktocpage = {true},
    plainpages = {false},
    linkcolor = {Blue},
    citecolor = {Blue},
    urlcolor = {Red},
    pdfstartview = {Fit},
    pdfpagemode = {UseOutlines},
    pdfview = {XYZ null null null}
  }

\begin{document}

\maketitle

\section{Introduction}
\label{sec:introduction}

\pkg{actuar} \citep{actuar} is a package providing additional
Actuarial Science functionality to the \proglang{R} statistical
system. Although various packages on the Comprehensive \proglang{R}
Archive Network (CRAN) provide functions useful to actuaries,
\pkg{actuar} aims to serve as a central location for more specifically
actuarial functions and data sets. The project was officially launched
in 2005 and is under active development.

The current feature set of the package can be split in four main
categories: loss distributions modeling, risk theory (including ruin
theory), simulation of compound hierarchical models and credibility
theory.

As much as possible, the developers have tried to keep the ``user
interface'' of the various functions of the package consistent.
Moreover, the package follows the general \proglang{R} philosophy of
working with model objects. This means that instead of merely
returning, say, a vector of probabilities, many functions will return
an object containing, among other things, the said probabilities. The
object can then be manipulated at one's will using various extraction,
summary or plotting functions.



\section{Documentation}

It is a requirement of the \proglang{R} packaging system that every
function and data set in a package has a help page. The \pkg{actuar}
package follows this requirement strictly. In addition to the help
pages, the package includes vignettes and demonstration scripts;
running
<<echo=TRUE, eval=FALSE>>=
vignette(package = "actuar")
@
and
<<eval=FALSE>>=
demo(package = "actuar")
@
at the \proglang{R} prompt will give the list of each.


\section{Collaboration and citation}

Obviously, the package leaves many other fields of Actuarial Science
untouched. For this situation to change, we hope that experts in their
field will join their efforts to ours and contribute code to the
\pkg{actuar} project. The project will continue to grow and to improve
by and for the community of developers and users.

If you use \proglang{R} or \pkg{actuar} for actuarial analysis, please
cite the software in publications. Use
<<eval=FALSE>>=
citation()
@
or
<<eval=FALSE>>=
citation("actuar")
@
for information on how to cite the software.


\section*{Acknowledgments}

The package would not be at this stage of development without the
stimulating contribution of Sébastien Auclair, Xavier Milhaud,
Tommy Ouellet and Louis-Philippe Pouliot.

This research benefited from financial support from the Natural
Sciences and Engineering Research Council of Canada and from the
\emph{Chaire d'actuariat} (Actuarial Science Foundation) of Université
Laval.

\bibliography{actuar}

\end{document}

%%% Local Variables:
%%% mode: latex
%%% TeX-master: t
%%% coding: utf-8
%%% End:
